/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;
// import Images package

//import Images.*;
import Entities.Customer;
import Entities.LotSpecs;
import Entities.Payment;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;

/**
 *
 * @author Smurf
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form LotSpecs
     */
    String price1 = "3200000";
    String price2 = "12500000";
    String price3 = "25000000";
    ArrayList<Customer> customers = new ArrayList<>();

    String currentPrice;
    String selectedCity;
    String selectedModel;
    String reservationDayCount;

    int dayCount;
    String stat;
    String daysReserved;

    String header[] = new String[]{"First name", "Surname", "Email", "Contact no.", "Block location", "Lot size (sq. m)", "Price", "MOP", "Status", "Reserved for"};
    DefaultTableModel dtm;
    int row, col;
    // create a filestream object
    FileOutputStream fos;

    // initialize an arraylist for lot
    // create a function that randomly chooses 0 or 1
    public int random() {
        int random = (int) (Math.random() * 2);
        return random;
    }

    public MainUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        dtm = new DefaultTableModel(header, 0);

        PropRecords.setModel(dtm);
        PropRecords.setEnabled(false);
        this.setLayout(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MoPbox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        FirstNameField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        LastNameField = new javax.swing.JTextField();
        RegisterButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        ContactField = new javax.swing.JTextField();
        DurationLabel = new javax.swing.JLabel();
        DaysLabel = new javax.swing.JLabel();
        ResDayCount = new javax.swing.JTextField();
        ClearFields = new javax.swing.JButton();
        isReservation = new javax.swing.JComboBox<>();
        LocationSelection = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PropRecords = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        PrintButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LotSizeSelection = new javax.swing.JTextField();
        PriceField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 0));
        setForeground(new java.awt.Color(153, 255, 204));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Lot Specifications");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Lot size (in sq. meters)");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Location (Block no.)");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Payment and Checkout");

        MoPbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Card" }));
        MoPbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoPboxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mode of payment");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Price");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Reservation");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Customer Details");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("First name");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Last name");

        RegisterButton.setBackground(new java.awt.Color(51, 153, 255));
        RegisterButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setText("Register");
        RegisterButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RegisterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseClicked(evt);
            }
        });
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Email");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Contact no.");

        ContactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactFieldActionPerformed(evt);
            }
        });

        DurationLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DurationLabel.setText("Duration");

        DaysLabel.setText("Days");

        ResDayCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResDayCountActionPerformed(evt);
            }
        });

        ClearFields.setBackground(new java.awt.Color(255, 0, 0));
        ClearFields.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ClearFields.setForeground(new java.awt.Color(255, 255, 255));
        ClearFields.setText("Clear");
        ClearFields.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ClearFields.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearFieldsMouseClicked(evt);
            }
        });

        isReservation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        isReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isReservationActionPerformed(evt);
            }
        });

        LocationSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        LocationSelection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LocationSelectionMouseClicked(evt);
            }
        });
        LocationSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationSelectionActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel6.setText("REAL-ESTATE SALES & MANAGEMENT SYSTEM");

        PropRecords.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PropRecords.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PropRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        PropRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PropRecordsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PropRecords);

        jLabel15.setText("+63");

        PrintButton.setBackground(new java.awt.Color(0, 153, 0));
        PrintButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PrintButton.setForeground(new java.awt.Color(255, 255, 255));
        PrintButton.setText("Print");
        PrintButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PrintButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrintButtonMouseClicked(evt);
            }
        });
        PrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintButtonActionPerformed(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(102, 102, 102));
        ExitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("Exit");
        ExitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
        });
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(265, 265, 265)
                .addComponent(jLabel13)
                .addGap(336, 336, 336))
            .addGroup(layout.createSequentialGroup()
                .addGap(395, 395, 395)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel2)))
                        .addGap(99, 99, 99)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ContactField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(111, 111, 111)
                                        .addComponent(LastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ClearFields, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(jLabel10)
                                .addGap(250, 250, 250)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(273, 273, 273)
                                .addComponent(jLabel9))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(MoPbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(259, 259, 259)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(isReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8)
                                        .addComponent(LocationSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(126, 126, 126)
                                            .addComponent(LotSizeSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(138, 138, 138)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(DurationLabel)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(ResDayCount, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(PrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(DaysLabel)))))))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(627, 627, 627)
                            .addComponent(jLabel5))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LotSizeSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocationSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(DurationLabel))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MoPbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResDayCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DaysLabel))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearFields, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearFieldsMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ClearFieldsMouseClicked
        // clear all fields
        FirstNameField.setText("");
        LastNameField.setText("");
        EmailField.setText("");
        ContactField.setText("");
        ResDayCount.setText("");
        LotSizeSelection.setText("");
        PriceField.setText("");

    }// GEN-LAST:event_ClearFieldsMouseClicked

    private void isReservationActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_isReservationActionPerformed
        String reservChoice = isReservation.getSelectedItem().toString();
        if ("Yes".equals(reservChoice)) {
            DurationLabel.setEnabled(true);
            ResDayCount.setEnabled(true);
            DaysLabel.setEnabled(true);
        } else {
            DurationLabel.setEnabled(false);
            ResDayCount.setEnabled(false);
            DaysLabel.setEnabled(false);
        }
    }// GEN-LAST:event_isReservationActionPerformed

    private void LocationSelectionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LocationSelectionActionPerformed
        selectedCity = LocationSelection.getSelectedItem().toString();
    }// GEN-LAST:event_LocationSelectionActionPerformed

    private void LocationSelectionMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_LocationSelectionMouseClicked

    }// GEN-LAST:event_LocationSelectionMouseClicked

    private void PropRecordsMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_PropRecordsMouseClicked
    }// GEN-LAST:event_PropRecordsMouseClicked

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RegisterButtonActionPerformed
    }// GEN-LAST:event_RegisterButtonActionPerformed

    private void PrintButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_PrintButtonMouseClicked
        // save customers arraylist to txt
        try {

            PrintWriter writer = new PrintWriter("customers.txt", "UTF-8");
            for (int i = 0; i < customers.size(); i++) {
                writer.println("RECORD " + (i + 1) + "\n" + "Name: " + customers.get(i).getFirstName() + " " + customers.get(i).getLastName() + "\n" + "Email: " + customers.get(i).getEmail() + "\n" + "Contact no.: " + customers.get(i).getContactNo() + "\n" + "Block location: " + customers.get(i).getLotspecs().getLocation() + "\n" + "Lot size: " + customers.get(i).getLotspecs().getLotSize() + "\n" + "Price: " + customers.get(i).getLotspecs().getPrice() + "\n" + "Mode of payment: " + customers.get(i).getPayment().getModeOfPayment() + "\n" + "Lot status: " + customers.get(i).getStatus() + "\n" + "Reservation duration: " + customers.get(i).getDaysReserved() + "\n\n");
            }
            writer.close();

            JOptionPane.showMessageDialog(null, "Records have been saved to txt file!");
        } catch (IOException e) {

        }

    }// GEN-LAST:event_PrintButtonMouseClicked

    private void PrintButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PrintButtonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_PrintButtonActionPerformed

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ExitButtonMouseClicked
        int confirmed = JOptionPane.showConfirmDialog(null, "Exit Program?", "EXIT CONFIRMATION",
                JOptionPane.YES_NO_OPTION);
        if (confirmed == JOptionPane.YES_OPTION) {
            dispose();
        }
    }// GEN-LAST:event_ExitButtonMouseClicked

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ExitButtonActionPerformed
    }// GEN-LAST:event_ExitButtonActionPerformed

    private void MoPboxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed

    }// GEN-LAST:event_jComboBox1ActionPerformed

    private void ContactFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ContactFieldActionPerformed
    }// GEN-LAST:event_ContactFieldActionPerformed

    private void YesReservationChoiceMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_YesReservationChoiceMouseClicked
        DurationLabel.setVisible(true);
        ResDayCount.setEnabled(true);
        ResDayCount.setVisible(true);
        DaysLabel.setVisible(true);

    }// GEN-LAST:event_YesReservationChoiceMouseClicked

    private void NoReservationChoiceMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_NoReservationChoiceMouseClicked
        DurationLabel.setVisible(false);
        ResDayCount.setEnabled(false);
        ResDayCount.setVisible(false);
        DaysLabel.setVisible(false);
    }// GEN-LAST:event_NoReservationChoiceMouseClicked

    private void RegisterButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_RegisterButtonMouseClicked
        if (FirstNameField.getText().isEmpty() || LastNameField.getText().isEmpty() || EmailField.getText().isEmpty()
                || ContactField.getText().isEmpty() || LotSizeSelection.getText().isEmpty() || PriceField.getText().isEmpty() || ResDayCount.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the missing data!");
        } else {
            try {
                String firstName = FirstNameField.getText();
                String lastName = LastNameField.getText();
                String email = EmailField.getText();
                int contact = Integer.parseInt(ContactField.getText());
                String locationBlock = LocationSelection.getSelectedItem().toString();
                String sqMet = LotSizeSelection.getText();
                String price = PriceField.getText();
                String mop = MoPbox.getSelectedItem().toString();
                if ("Yes".equals(isReservation.getSelectedItem().toString())) {
                    daysReserved = ResDayCount.getText() + " Days";
                    stat = "RESERVED";
                } else if ("No".equals(isReservation.getSelectedItem().toString())) {
                    daysReserved = "ALREADY SOLD";
                    stat = "SOLD";
                }
                customers.add(new Customer(firstName, lastName, email, contact, new LotSpecs(locationBlock, sqMet, price), new Payment(mop), stat, daysReserved));
                dtm.setRowCount(0);

                for (int i = 0; i < customers.size(); i++) {
                    Object[] fields = {customers.get(i).getFirstName(),
                        customers.get(i).getLastName(), customers.get(i).getEmail(),
                        customers.get(i).getContactNo(),
                        customers.get(i).getLotspecs().getLocation(), customers.get(i).getLotspecs().getLotSize(),
                        customers.get(i).getLotspecs().getPrice(),
                        customers.get(i).getPayment().getModeOfPayment(), customers.get(i).getStatus(), customers.get(i).getDaysReserved()};
                    dtm.addRow(fields);
                }
                clearFields();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Double check your values for contact number, lot size, and price");
            }
        }
    }// GEN-LAST:event_RegisterButtonMouseClicked

    private void ResDayCountActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ResDayCountActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_ResDayCountActionPerformed

    /**
     * @param args the command line arguments
     */
    void clearFields() {
        FirstNameField.setText("");
        LastNameField.setText("");
        EmailField.setText("");
        ContactField.setText("");

        LotSizeSelection.setText("");
        PriceField.setText("");

        DurationLabel.setEnabled(false);
        if ("Yes".equals(isReservation.getSelectedItem().toString())) {
            ResDayCount.setEnabled(true);
        } else {

            ResDayCount.setText("");
            ResDayCount.setEnabled(false);
            DaysLabel.setEnabled(false);

        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainUI window = new MainUI();
                window.setVisible(true);// <-- the title bar is removed here
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearFields;
    private javax.swing.JTextField ContactField;
    private javax.swing.JLabel DaysLabel;
    private javax.swing.JLabel DurationLabel;
    private javax.swing.JTextField EmailField;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JComboBox<String> LocationSelection;
    private javax.swing.JTextField LotSizeSelection;
    private javax.swing.JComboBox<String> MoPbox;
    private javax.swing.JTextField PriceField;
    private javax.swing.JButton PrintButton;
    private javax.swing.JTable PropRecords;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JTextField ResDayCount;
    private javax.swing.JComboBox<String> isReservation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
