/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;
import Entities.*;
import java.util.ArrayList;

/**
 *
 * @author Smurf
 */
public class Main extends javax.swing.JFrame {

    // initialize a customer object and create an arraylist of customers
    public Customer customer = new Customer();
    public ArrayList<Customer> customers = new ArrayList<>();

    /**
     * Creates new form Login
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginNameLabel = new javax.swing.JLabel();
        LoginEmailLabel = new javax.swing.JLabel();
        LoginAddressLabel = new javax.swing.JLabel();
        LoginAddressField = new javax.swing.JTextField();
        LoginNameField = new javax.swing.JTextField();
        LoginEmailField = new javax.swing.JTextField();
        LeftPaneColor = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        LoginTitleLabel = new javax.swing.JLabel();
        LoginSubmitButton = new javax.swing.JButton();
        FieldsAreEmptyLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LoginNameLabel.setText("Name");

        LoginEmailLabel.setText("Email");

        LoginAddressLabel.setText("Address");

        LoginNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginNameFieldActionPerformed(evt);
            }
        });

        LeftPaneColor.setBackground(new java.awt.Color(0, 102, 102));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Real Estate Sales and Management System");

        javax.swing.GroupLayout LeftPaneColorLayout = new javax.swing.GroupLayout(LeftPaneColor);
        LeftPaneColor.setLayout(LeftPaneColorLayout);
        LeftPaneColorLayout.setHorizontalGroup(
            LeftPaneColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftPaneColorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(20, 20, 20))
        );
        LeftPaneColorLayout.setVerticalGroup(
            LeftPaneColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPaneColorLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LoginTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LoginTitleLabel.setText("Sign-in Form");

        LoginSubmitButton.setText("Submit");
        LoginSubmitButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LoginSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginSubmitButtonActionPerformed(evt);
            }
        });

        FieldsAreEmptyLabel.setForeground(new java.awt.Color(255, 51, 51));
        FieldsAreEmptyLabel.setText(".");
        FieldsAreEmptyLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(LeftPaneColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(LoginAddressLabel)
                        .addComponent(LoginNameLabel)
                        .addComponent(LoginEmailLabel)
                        .addComponent(LoginEmailField, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                        .addComponent(LoginAddressField)
                        .addComponent(LoginTitleLabel)
                        .addComponent(LoginNameField))
                    .addComponent(LoginSubmitButton)
                    .addComponent(FieldsAreEmptyLabel))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(LoginTitleLabel)
                .addGap(32, 32, 32)
                .addComponent(LoginNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoginNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(LoginEmailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoginEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(LoginAddressLabel)
                .addGap(18, 18, 18)
                .addComponent(LoginAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LoginSubmitButton)
                .addGap(69, 69, 69)
                .addComponent(FieldsAreEmptyLabel)
                .addGap(50, 50, 50))
            .addComponent(LeftPaneColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginSubmitButtonActionPerformed
        if (LoginNameField.getText().isEmpty() || LoginEmailField.getText().isEmpty() || LoginAddressField.getText().isEmpty()) {
            FieldsAreEmptyLabel.setText("Please enter the necessary details!");
        } else {
            
            this.setVisible(false);
            // show LotSpecs 
            LotSpecs lotSpecs = new LotSpecs();
            lotSpecs.setVisible(true);
            
        }
    }//GEN-LAST:event_LoginSubmitButtonActionPerformed

    private void LoginNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginNameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main window = new Main();
                window.setResizable(false);
                window.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FieldsAreEmptyLabel;
    private javax.swing.JPanel LeftPaneColor;
    private javax.swing.JTextField LoginAddressField;
    private javax.swing.JLabel LoginAddressLabel;
    private javax.swing.JTextField LoginEmailField;
    private javax.swing.JLabel LoginEmailLabel;
    private javax.swing.JTextField LoginNameField;
    private javax.swing.JLabel LoginNameLabel;
    private javax.swing.JButton LoginSubmitButton;
    private javax.swing.JLabel LoginTitleLabel;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
