/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;
// import Images package

//import Images.*;
import Entities.Customer;
import Entities.LotSpecs;
import Entities.Payment;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author Smurf
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form LotSpecs
     */
    String price1 = "3200000";
    String price2 = "12500000";
    String price3 = "25000000";

    String currentPrice;
    String selectedCity;
    String selectedModel;
    String reservationDayCount;

    int dayCount;

    public Register() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        MoPbox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        FirstNameField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        LastNameField = new javax.swing.JTextField();
        RegisterButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        ContactField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        DurationLabel = new javax.swing.JLabel();
        DaysLabel = new javax.swing.JLabel();
        TotalPrice = new javax.swing.JLabel();
        ResDayCount = new javax.swing.JTextField();
        sqMeters = new javax.swing.JTextField();
        ClearFields = new javax.swing.JButton();
        MoPbox1 = new javax.swing.JComboBox<>();
        LocationSelection = new javax.swing.JComboBox<>();
        ModelSelection = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Lot Specifications");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Lot size (in sq. meters)");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Location");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Payment and Checkout");

        MoPbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Card" }));
        MoPbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoPboxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mode of payment");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Model");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Reservation");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Customer Details");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("First name");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Last name");

        RegisterButton.setBackground(new java.awt.Color(51, 153, 255));
        RegisterButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(0, 0, 0));
        RegisterButton.setText("Register");
        RegisterButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RegisterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Email");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Contact no.");

        ContactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactFieldActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Total");

        DurationLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DurationLabel.setText("Duration");

        DaysLabel.setText("Days");

        TotalPrice.setText("--");

        ResDayCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResDayCountActionPerformed(evt);
            }
        });

        ClearFields.setBackground(new java.awt.Color(255, 102, 102));
        ClearFields.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ClearFields.setForeground(new java.awt.Color(255, 255, 255));
        ClearFields.setText("Clear");
        ClearFields.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ClearFields.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearFieldsMouseClicked(evt);
            }
        });

        MoPbox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        MoPbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoPbox1ActionPerformed(evt);
            }
        });

        LocationSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makati, NCR", "Clark, Pampanga", "Bacolod, Negros" }));
        LocationSelection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LocationSelectionMouseClicked(evt);
            }
        });
        LocationSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationSelectionActionPerformed(evt);
            }
        });

        ModelSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humilis (Entry level)", "Semis (Mid level)", "Luxus (Top-of-the-line)" }));
        ModelSelection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModelSelectionMouseClicked(evt);
            }
        });
        ModelSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelSelectionActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("REAL-ESTATE SALES & MANAGEMENT SYSTEM");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Register");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Records");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)
                            .addComponent(jLabel14)
                            .addComponent(TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(MoPbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(112, 112, 112)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ResDayCount, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DaysLabel))
                                    .addComponent(DurationLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(LocationSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(sqMeters, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(ModelSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addGap(50, 50, 50)
                                            .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(18, 18, 18)
                                            .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(24, 24, 24)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(26, 26, 26)
                                            .addComponent(LastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(18, 18, 18)
                                            .addComponent(ContactField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MoPbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ClearFields, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(34, 34, 34)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(LastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(ContactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sqMeters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocationSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModelSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(DurationLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MoPbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MoPbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResDayCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DaysLabel))
                .addGap(29, 29, 29)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TotalPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearFields, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearFieldsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearFieldsMouseClicked
        // clear all fields
        FirstNameField.setText("");
        LastNameField.setText("");
        EmailField.setText("");
        ContactField.setText("");
        sqMeters.setText("");
        TotalPrice.setText("");
        ResDayCount.setText("");

    }//GEN-LAST:event_ClearFieldsMouseClicked

    private void MoPbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoPbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoPbox1ActionPerformed

    private void LocationSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationSelectionActionPerformed
        selectedCity = LocationSelection.getSelectedItem().toString();
    }//GEN-LAST:event_LocationSelectionActionPerformed

    private void ModelSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelSelectionActionPerformed
        selectedModel = ModelSelection.getSelectedItem().toString();
        TotalPrice.setText("");
        if (selectedModel == "Humilis (Entry level)") {
            TotalPrice.setText(price1);
        } else if (selectedModel == "Semis (Mid level)") {
            TotalPrice.setText(price2);
        } else if (selectedModel == "Luxus (Top-of-the-line)") {
            TotalPrice.setText(price3);
        }
    }//GEN-LAST:event_ModelSelectionActionPerformed

    private void LocationSelectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LocationSelectionMouseClicked

    }//GEN-LAST:event_LocationSelectionMouseClicked

    private void ModelSelectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModelSelectionMouseClicked

    }//GEN-LAST:event_ModelSelectionMouseClicked

    private void MoPboxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed

    }// GEN-LAST:event_jComboBox1ActionPerformed

    private void LowEndHouseButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_LowEndHouseButtonMouseClicked

        currentPrice = price1;
        TotalPrice.setText(String.valueOf("Php" + currentPrice));

    }// GEN-LAST:event_LowEndHouseButtonMouseClicked

    private void MidEndHouseButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_MidEndHouseButtonMouseClicked

        currentPrice = price2;
        TotalPrice.setText(String.valueOf("Php" + currentPrice));

    }// GEN-LAST:event_MidEndHouseButtonMouseClicked

    private void HiEndHouseButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_HiEndHouseButtonMouseClicked

        currentPrice = price3;
        TotalPrice.setText(String.valueOf("Php" + currentPrice));

    }// GEN-LAST:event_HiEndHouseButtonMouseClicked

    private void ContactFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ContactFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_ContactFieldActionPerformed

    private void YesReservationChoiceMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_YesReservationChoiceMouseClicked
        DurationLabel.setVisible(true);
        ResDayCount.setEnabled(true);
        ResDayCount.setVisible(true);
        DaysLabel.setVisible(true);

    }// GEN-LAST:event_YesReservationChoiceMouseClicked

    private void NoReservationChoiceMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_NoReservationChoiceMouseClicked
        DurationLabel.setVisible(false);
        ResDayCount.setEnabled(false);
        ResDayCount.setVisible(false);
        DaysLabel.setVisible(false);
    }// GEN-LAST:event_NoReservationChoiceMouseClicked

    private void RegisterButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_RegisterButtonMouseClicked
        if (FirstNameField.getText().isEmpty() || LastNameField.getText().isEmpty() || EmailField.getText().isEmpty()
                || ContactField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the missing data!");
        } else {
            // store multiple Customers in a list
            ArrayList<Customer> customers = new ArrayList<>();
            // get customer info 
            customers.add(new Customer(FirstNameField.getText(), LastNameField.getText(), EmailField.getText(), ContactField.getText(), new LotSpecs(sqMeters.getText(), LocationSelection.getSelectedItem().toString(), ModelSelection.getSelectedItem().toString()), new Payment(MoPbox.getSelectedItem().toString())));
            // print arraylist
            for (Customer c : customers) {
                System.out.println(c.getFirstName() + " " + c.getLastName() + " " + c.getEmail() + " " + c.getContactNo() + " " + c.getLotspecs().getLotSize() + " " + c.getLotspecs().getLocation() + " " + c.getLotspecs().getModel() + " " + c.getPayment().getModeOfPayment());
            }

        }
    }// GEN-LAST:event_RegisterButtonMouseClicked

    private void ResDayCountActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ResDayCountActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_ResDayCountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Register window = new Register();
                window.setResizable(false);
                window.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearFields;
    private javax.swing.JTextField ContactField;
    private javax.swing.JLabel DaysLabel;
    private javax.swing.JLabel DurationLabel;
    private javax.swing.JTextField EmailField;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JComboBox<String> LocationSelection;
    private javax.swing.JComboBox<String> MoPbox;
    private javax.swing.JComboBox<String> MoPbox1;
    private javax.swing.JComboBox<String> ModelSelection;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JTextField ResDayCount;
    private javax.swing.JLabel TotalPrice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField sqMeters;
    // End of variables declaration//GEN-END:variables
}
